# def hello():
#     print("hello eddy")

# hello()
# hello()



# def greet(name):
#     print("welcome" , name)


# greet("aditya")
# greet("eddy")


# # add 
# def add(a, b):
#     print(a+b)

# add(5, 7)


# RETURNING MULTIPLE VALUE
# def ADD(a, b):
#     z = a + b
#     return  z

# def SUB(a, b):
#     z = a - b
#     return  z

# def MULTIPY(a, b):
#     z = a * b
#     return  z

# def DIVIDE(a, b):
#     z = a / b
#     return  z


# print (ADD(5 , 4))
# print (SUB(5 , 4))
# print (MULTIPY(5 , 4))
# print (DIVIDE(5 , 4))



