# # def addition (numbers = ["--x", "x++","x++"]):
       

# #        x = 0
# #       #  numbers = ["--x", "x++","x++"]
# #        for number in numbers:
# #               if number =="--x":
# #                      x = x-1
                     
# #               if number == "x++":
# #                   x = x+1
                  
             
                                   
                                   
# #        return (x)


# # print(addition( ["--x", "x++","x++"]))
# # 
# # 
# def hello(a):

#     result = 0

#     for a in range (a):
#         if a % 3 == 0:
#             result = result + a

#         if a % 5 == 0:
#             result = result + a

#         if a % 7 == 0:
#             result = result + a

#     return (result)


# print(hello(8))



# cube = lambda x: x*x*x

# print(cube(3))


# string = lambda x: x[-1]

# print(string("Aditya"))

# difference = lambda a,b: abs(a-b) 

# print(difference(4, 10))



maximum = lambda a, b, c: a > b  and a > c  or b > a and b > c or c > a and c > b 


print (maximum(5,10,15))

        



