def addition (numbers = ["--x", "x++","x++"]):
       

#        x = 0
#       #  numbers = ["--x", "x++","x++"]
#        for number in numbers:
#               if number =="--x":
#                      x = x-1
                     
#               if number == "x++":
#                   x = x+1
                  
             
                                   
                                   
#        return (x)


# print(addition( ["--x", "x++","x++"]))
             
